Pair programming - MODULO 3 - LECCION 01

In [3]:
import numpy as np

Creación y Indexación:
1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las
posiciones múltiplos de 5.
2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para
obtener los elementos en las posiciones impares.
3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar
comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben
estar redondeados a 2 decimales.
4. Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la
segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.
5. Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores
negativos.
6. Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los
elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos?
7. Crea un array 1D con 40 valores del 1 al 100 (ambos incluidos). Obtén los elementos que
son divisibles por 3 y por 4.
8. BONUS: Crea un array 3D de forma (2, 3, 5) y 50 elementos con números enteros entre 0
y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [11]:
array1 = np.random.randint(10, 100,(50))
array1

array([73, 51, 52, 90, 75, 39, 60, 36, 93, 76, 82, 84, 26, 82, 29, 80, 95,
       64, 67, 65, 36, 83, 33, 71, 77, 88, 20, 26, 25, 34, 63, 43, 82, 26,
       43, 48, 59, 72, 41, 73, 58, 59, 81, 27, 72, 13, 54, 91, 96, 38])

In [14]:
# Acceder a los elementos en las posiciones 
array1[4::5]

array([75, 76, 29, 65, 77, 34, 43, 73, 72, 38])

In [19]:
# 2
array2 = np.random.randint(1, 21, (30))
array2

array([20,  9,  6, 17, 20, 10, 18, 10, 12, 11, 13, 16, 18,  1, 18,  7,  2,
       13, 17, 11, 10, 20, 19,  4, 18, 12,  4,  2, 14,  1])

In [20]:
array2[0::2]

array([20,  6, 20, 18, 12, 13, 18, 18,  2, 17, 10, 19, 18,  4, 14])

In [38]:
# 3
array3 = np.random.randint(10, 100, (4,6))
array3

array([[63, 56, 18, 61, 84, 60],
       [20, 38, 34, 66, 64, 76],
       [10, 53, 29, 13, 24, 89],
       [61, 28, 65, 59, 39, 35]])

In [37]:
ultima_fila_redondeo = np.round(array3[-1], 2)
ultima_fila_redondeo

array([52, 78, 96, 36, 63, 99])

In [27]:
#redondeo
array3redondeo = np.round(array3, 2)
array3redondeo

array([[[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000, 3.59751658e+252, 1.46901661e+179],
        [8.37404147e+242, 0.00000000e+000, 4.82337723e+228,
         0.00000000e+000, 6.85977797e+169, 0.00000000e+000],
        [0.00000000e+000, 7.63226654e+169, 5.04621343e+180,
         0.00000000e+000, 2.36155100e+180, 0.00000000e+000],
        [0.00000000e+000, 1.16279102e+165, 0.00000000e+000,
         9.08366791e+223, 0.00000000e+000, 0.00000000e+000]]])

In [40]:
#4. Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.
array4 = np.random.rand(6, 4)
array4

array([[0.70658872, 0.95796974, 0.87811787, 0.30296503],
       [0.6010035 , 0.84180918, 0.20256969, 0.15052955],
       [0.24938969, 0.87951074, 0.02954979, 0.20510592],
       [0.98803898, 0.95689181, 0.28241428, 0.23483274],
       [0.10337843, 0.61881683, 0.74509525, 0.68174091],
       [0.58821058, 0.84086537, 0.44117995, 0.24579992]])

In [68]:
redondeo4 = np.round(array4, 2)
redondeo4

array([[0.71, 0.96, 0.88, 0.3 ],
       [0.6 , 0.84, 0.2 , 0.15],
       [0.25, 0.88, 0.03, 0.21],
       [0.99, 0.96, 0.28, 0.23],
       [0.1 , 0.62, 0.75, 0.68],
       [0.59, 0.84, 0.44, 0.25]])

In [46]:
redondeo4 = np.round(array4[:,1], 2)
redondeo4

array([0.96, 0.84, 0.88, 0.96, 0.62, 0.84])

In [59]:
#5. Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores negativos.
array5 = np.random.randint(-50, 51, (30))
array5

array([ -6, -40,  24,  20,  45,  32,  -5,  32,  30,  28,   2, -49,  19,
       -43, -20, -25, -24,  44,  31,  19,  12,  19,  17,  11, -22,   4,
       -44,  -2, -49, -45])

In [60]:
valores_negativos = array5 [array5 < 0]
valores_negativos

array([ -6, -40,  -5, -49, -43, -20, -25, -24, -22, -44,  -2, -49, -45])

In [ ]:
# 6. Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos?

In [61]:
array6 = np.random.rand(10)
array6

array([0.09841207, 0.62377435, 0.94012073, 0.85912532, 0.98224019,
       0.60217927, 0.51654105, 0.685787  , 0.77840743, 0.52080806])

In [63]:
redondeo6 = np.round(array6, 2)
redondeo6

array([0.1 , 0.62, 0.94, 0.86, 0.98, 0.6 , 0.52, 0.69, 0.78, 0.52])

In [70]:
mayor_que05 = redondeo6[redondeo6 > 0.5]
mayor_que05

array([0.62, 0.94, 0.86, 0.98, 0.6 , 0.52, 0.69, 0.78, 0.52])

In [71]:
posicion = np.where(redondeo6 > 0.5)
posicion

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),)

In [ ]:
# 7. Crea un array 1D con 40 valores del 1 al 100 (ambos incluidos). Obtén los elementos que son divisibles por 3 y por 4.
# 8. BONUS: Crea un array 3D de forma (2, 3, 5) y 50 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [ ]:
# Reshape y Transpose:

In [ ]:
# 1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [81]:
array_tridimensional =  np.random.randint(1, 101,size=(2, 3, 4))
array_tridimensional

array([[[25, 85,  6, 16],
        [79, 20, 33, 63],
        [32, 80, 26, 46]],

       [[31,  7, 79, 12],
        [11, 96, 61,  3],
        [24, 81, 24, 89]]])

In [82]:
array_tridimensional.shape

(2, 3, 4)

In [83]:
array_tridi1 = array_tridimensional.reshape(2, -1)
array_tridi1

array([[25, 85,  6, 16, 79, 20, 33, 63, 32, 80, 26, 46],
       [31,  7, 79, 12, 11, 96, 61,  3, 24, 81, 24, 89]])

In [ ]:
# 2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [88]:
array_3d = np.random.randint(1, 60, (3, 4, 5))
array_3d

array([[[48, 40,  9, 42, 12],
        [17,  8, 27, 44, 57],
        [17, 18, 10, 22, 52],
        [35,  8, 23, 34, 59]],

       [[52, 24, 26, 13, 15],
        [19, 53, 48, 57, 31],
        [40,  3, 58,  1,  1],
        [54, 52, 34, 33, 41]],

       [[37,  6, 27, 13, 46],
        [58,  4, 22, 13, 30],
        [49, 34, 26, 50, 58],
        [11, 12, 56, 56, 57]]])

In [94]:
array_3d_convertido = array_3d.reshape(4, -1)
array_3d_convertido

array([[48, 40,  9, 42, 12, 17,  8, 27, 44, 57, 17, 18, 10, 22, 52],
       [35,  8, 23, 34, 59, 52, 24, 26, 13, 15, 19, 53, 48, 57, 31],
       [40,  3, 58,  1,  1, 54, 52, 34, 33, 41, 37,  6, 27, 13, 46],
       [58,  4, 22, 13, 30, 49, 34, 26, 50, 58, 11, 12, 56, 56, 57]])

In [ ]:
# 3. Crea un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1. Utiliza reshape para convertirlo en un array 2D.

In [ ]:
Ejercicios con transpose:
# 4. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).
array_3d = np.random.randint(1, 60, (3, 4, 5))
array_3d

In [96]:
array_transpose = np.transpose(array_3d, (5, 4, 3))
array_transpose

AxisError: axis 5 is out of bounds for array of dimension 3

In [ ]:
# 5. Utiliza el array 3D del ejercicio 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 2, 4).



In [ ]:
# Preguntas teóricas:
# 6. ¿Qué diferencia existe entre el reshape y el transpose?
# 7. ¿Y entre el transpose y el swapaxes?

In [ ]:

Funciones Aritméticas y Estadísticas:
1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo
tengan 1 decimal.
2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente.
Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero
basándonos en los valores del primer array bajo las siguientes condiciones:
Si el valor del array es igual que la media, se reemplaza por "A".
Si el valor del array es mayor que la media, se reemplaza por "B".
Si el valor del array es menor que la media, se reemplaza por "C".
Si el valor es igual que el máximo, se reemplaza por "D".
Si el valor es igual que el mínimo, se reemplaza por "E".
# a modo de ejemplo. Si tenemos el siguiente array
[[[0.4, 0.7, 0.2, 0.9, 0.2],
 [0.1, 0.9, 0.6, 0.1, 0.2],
 [1. , 0.2, 0.1, 0.8, 0.3]],
[[0. , 0.3, 0.4, 0.5, 0.1],
 [0.5, 0.7, 0.9, 0. , 0.8],
 [0.5, 0.3, 0.5, 0.8, 0.1]]])
# sabiendo que la media es 0.4 y el máximo es 1.0 y el mínimo es
0.0
# nuestro array vacío debería quedar como este: 
[[["A", "B", "C", "B", "C"],
 ["C", "B", "B", "C", "C"],
 ["D" , "C", "C", "B", "C"]],
[["E" , "C", "A", "B", "C"],
 ["B", "B","B", "E" , "B"],
 ["B", "C", "B", "B", "C"]]]