## PAIR PROGRAMMING - MODULO 3 - LECCION 01 - NUMPY

In [3]:
import numpy as np

Creación y Indexación:

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [3]:
# Creación de array 1D con 50 valores aleatorio del 10 al 99.
array1 = np.random.randint(10, 100,(50))
array1

array([59, 67, 22, 56, 19, 12, 71, 99, 85, 36, 54, 17, 94, 83, 56, 82, 46,
       97, 26, 65, 36, 77, 40, 43, 60, 72, 43, 60, 60, 34, 94, 97, 46, 59,
       18, 89, 65, 33, 29, 48, 45, 91, 46, 66, 74, 69, 74, 56, 25, 20])

In [4]:
# Acceder a los elementos en las posiciones multiplos de 5
array1[4::5]

array([19, 36, 56, 65, 60, 34, 18, 48, 74, 20])

2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [5]:
# Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos).
array2 = np.random.randint(1, 21, (30))
array2

array([19, 19,  6, 13,  1,  3,  2, 10,  8, 17, 20, 20, 11,  3, 15, 18, 16,
        7, 13,  4,  5,  6,  8, 19,  2, 12, 15,  9,  3,  2])

In [9]:
# Utiliza indexación para obtener los elementos en las posiciones impares.
array2[0::2]

array([19,  6,  1,  2,  8, 20, 11, 15, 16, 13,  5,  8,  2, 15,  3])

3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [32]:
# Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). 
array3 = np.random.uniform(10, 100, (4,6))
array3

array([[34.53838499, 97.80235626, 49.90597425, 84.4013752 , 10.09385065,
        16.64077705],
       [89.14099136, 75.73452077, 48.88559665, 59.07309272, 47.08374473,
        18.00893606],
       [13.49286095, 74.90720367, 72.97619413, 86.05226366, 47.86519681,
        87.85253693],
       [93.161343  , 31.55493417, 57.00451235, 58.89944532, 29.77975354,
        50.01899273]])

In [30]:
# Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.
ultima_fila_redondeo = np.round(array3[-1], 2)
ultima_fila_redondeo

array([80.85, 85.37, 38.1 , 24.81, 24.68, 49.11])

4. Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.

In [40]:
# Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. 
array4 = np.random.rand(6, 4)
array4

array([[0.70658872, 0.95796974, 0.87811787, 0.30296503],
       [0.6010035 , 0.84180918, 0.20256969, 0.15052955],
       [0.24938969, 0.87951074, 0.02954979, 0.20510592],
       [0.98803898, 0.95689181, 0.28241428, 0.23483274],
       [0.10337843, 0.61881683, 0.74509525, 0.68174091],
       [0.58821058, 0.84086537, 0.44117995, 0.24579992]])

In [68]:
# Recondeo de los números a 2 decimales
redondeo4 = np.round(array4, 2)
redondeo4

array([[0.71, 0.96, 0.88, 0.3 ],
       [0.6 , 0.84, 0.2 , 0.15],
       [0.25, 0.88, 0.03, 0.21],
       [0.99, 0.96, 0.28, 0.23],
       [0.1 , 0.62, 0.75, 0.68],
       [0.59, 0.84, 0.44, 0.25]])

In [46]:
# Accede a la segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.
redondeo4 = np.round(array4[:,1], 2)
redondeo4

array([0.96, 0.84, 0.88, 0.96, 0.62, 0.84])

5. Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores negativos.

In [59]:
# Crear un array 1D con 30 valores enteros aleatorios entre -50 y 50.
array5 = np.random.randint(-50, 51, (30))
array5

array([ -6, -40,  24,  20,  45,  32,  -5,  32,  30,  28,   2, -49,  19,
       -43, -20, -25, -24,  44,  31,  19,  12,  19,  17,  11, -22,   4,
       -44,  -2, -49, -45])

In [60]:
# Extrae los valores negativos.
valores_negativos = array5 [array5 < 0]
valores_negativos

array([ -6, -40,  -5, -49, -43, -20, -25, -24, -22, -44,  -2, -49, -45])

6. Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos?

In [61]:
# Crear un array 1D con 10 valores entre 0 y 1. 
array6 = np.random.rand(10)
array6

array([0.09841207, 0.62377435, 0.94012073, 0.85912532, 0.98224019,
       0.60217927, 0.51654105, 0.685787  , 0.77840743, 0.52080806])

In [63]:
# Redondea los decimales a 2. 
redondeo6 = np.round(array6, 2)
redondeo6

array([0.1 , 0.62, 0.94, 0.86, 0.98, 0.6 , 0.52, 0.69, 0.78, 0.52])

In [70]:
# Obtener los elementos cuyo valor es mayor que 0.5. 
mayor_que05 = redondeo6[redondeo6 > 0.5]
mayor_que05

array([0.62, 0.94, 0.86, 0.98, 0.6 , 0.52, 0.69, 0.78, 0.52])

In [71]:
# ¿En que posición/es están esos elementos?
posicion = np.where(redondeo6 > 0.5)
posicion

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),)

7. Crea un array 1D con 40 valores del 1 al 100 (ambos incluidos). Obtén los elementos que son divisibles por 3 y por 4.

In [33]:
# Crear un array 1D con 40 valores del 1 al 100 (ambos incluidos)
array1_40 = np.random.randint(1,101,(40))
array1_40

array([ 52,  36,  87,  50,  48,  43,   6,   1,  90,  46,  85,  84,  85,
        78,  88,  20,   3,  84,  29,   3,  61,  65,  34,  75,   2,  52,
        31, 100,  46,   1,  70,  35,  40,  32,  50,  71,  50,  83,  18,
        17])

In [35]:
# Obtener los elementos que son divisibles por 3 y por 4.
divisibles = array1_40[(array1_40 % 3 == 0) & (array1_40 % 4 == 0)]
divisibles

array([36, 48, 84, 84])

8. BONUS: Crea un array 3D de forma (2, 3, 5) y con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [74]:
# Crear un array 3D de forma (2, 3, 5) y con números enteros entre 0 y 100 (ambos incluidos). 
array_tridimensional =  np.random.randint(0, 101,(2,3,5))
array_tridimensional

array([[[ 52,  65,  66,  93,   6],
        [ 37,  91,  45,  38,  59],
        [ 99,  28,  72,  39,   2]],

       [[ 51,  96,  16,  65,  35],
        [ 58,  55,  77,  44,   8],
        [ 32,  63,  56,   1, 100]]])

In [77]:
# Reemplazar los elementos en posiciones múltiplos de 3 por 0.
array_tridimensional[array_tridimensional % 3 == 0] = 0 
array_tridimensional

array([[[ 52,  65,   0,   0,   0],
        [ 37,  91,   0,  38,  59],
        [  0,  28,   0,   0,   2]],

       [[  0,   0,  16,  65,  35],
        [ 58,  55,  77,  44,   8],
        [ 32,   0,  56,   1, 100]]])

# Reshape y Transpose:

1. Crear un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [36]:
array_tridimensional =  np.random.randint(1, 101,(2, 3, 4))
array_tridimensional

array([[[71, 27, 24, 30],
        [87, 16, 24, 35],
        [91,  9, 21,  9]],

       [[12, 76, 17, 81],
        [34,  4, 77, 72],
        [32, 72, 87, 93]]])

In [38]:
# Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.
array_tridi1 = array_tridimensional.reshape(2, -1)
array_tridi1

array([[71, 27, 24, 30, 87, 16, 24, 35, 91,  9, 21,  9],
       [12, 76, 17, 81, 34,  4, 77, 72, 32, 72, 87, 93]])

2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [88]:
# Crear un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). 
array_3d = np.random.randint(1, 60, (3, 4, 5))
array_3d

array([[[48, 40,  9, 42, 12],
        [17,  8, 27, 44, 57],
        [17, 18, 10, 22, 52],
        [35,  8, 23, 34, 59]],

       [[52, 24, 26, 13, 15],
        [19, 53, 48, 57, 31],
        [40,  3, 58,  1,  1],
        [54, 52, 34, 33, 41]],

       [[37,  6, 27, 13, 46],
        [58,  4, 22, 13, 30],
        [49, 34, 26, 50, 58],
        [11, 12, 56, 56, 57]]])

In [42]:
# Utilizar reshape para convertirlo en un array 2D.
array_3d_convertido = array_3d.reshape(5, -1)
array_3d_convertido

array([[37, 23,  2, 38, 18, 26, 40, 44, 27, 43, 35,  2],
       [16, 51, 59,  4, 35, 40, 52, 11, 28, 48, 40, 17],
       [ 7, 57, 32, 33, 17, 27,  4, 33, 20, 57, 59, 11],
       [13, 37, 38, 17, 43, 12, 25, 30,  3, 54, 17,  4],
       [20, 37, 19, 22, 42, 19, 32, 40,  3, 20, 53, 54]])

3. Crea un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1. Utiliza reshape para convertirlo en un array 2D.

In [45]:
# Crear un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1.
array33 = np.random.rand(4,3,2)
array33

array([[[0.8142176 , 0.03512689],
        [0.16814899, 0.89344669],
        [0.71096594, 0.20665172]],

       [[0.74466159, 0.66400599],
        [0.82287272, 0.11362154],
        [0.11728089, 0.47455893]],

       [[0.53884864, 0.06319869],
        [0.91107487, 0.03790459],
        [0.78473044, 0.86674891]],

       [[0.37943206, 0.20726946],
        [0.7342095 , 0.46883081],
        [0.93615988, 0.90943444]]])

In [50]:
# Utilizar reshape para convertirlo en un array 2D.
array33x = array33.reshape(4, -1)
array33x

array([[0.8142176 , 0.03512689, 0.16814899, 0.89344669, 0.71096594,
        0.20665172],
       [0.74466159, 0.66400599, 0.82287272, 0.11362154, 0.11728089,
        0.47455893],
       [0.53884864, 0.06319869, 0.91107487, 0.03790459, 0.78473044,
        0.86674891],
       [0.37943206, 0.20726946, 0.7342095 , 0.46883081, 0.93615988,
        0.90943444]])

# Transpose:

4. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [10]:
# Utilizar el array 3D del ejercicio 2 de reshape. 
array_3d = np.random.randint(1, 60, (3, 4, 5))
array_3d

array([[[57, 24, 17,  9, 46],
        [58,  6, 21, 18, 21],
        [ 5,  8, 32, 21, 36],
        [21, 41, 57, 12, 54]],

       [[12, 27, 57, 13, 38],
        [24,  3, 32, 54,  4],
        [31, 22, 21, 20, 37],
        [ 9, 26, 57, 32, 49]],

       [[18, 44, 46, 45, 41],
        [23, 36, 14, 11, 56],
        [56,  7,  8, 36, 23],
        [46, 25, 24, 47, 34]]])

In [51]:
# Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).
array_transpose = np.transpose(array_3d, (2, 1, 0)) # Ordenar con los indices
array_transpose

array([[[37, 28, 43],
        [26, 57, 54],
        [35,  4, 19],
        [ 4, 11, 40]],

       [[23, 48, 12],
        [40, 32, 17],
        [ 2, 33, 22],
        [35, 13,  3]],

       [[ 2, 40, 25],
        [44, 33,  4],
        [16, 20, 42],
        [40, 37, 20]],

       [[38, 17, 30],
        [27, 17, 20],
        [51, 57, 19],
        [52, 38, 53]],

       [[18,  7,  3],
        [43, 27, 37],
        [59, 59, 32],
        [11, 17, 54]]])

5. Utiliza el array 3D del ejercicio 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 2, 4).

In [13]:
# Utilizar el array 3D del ejercicio 4 de reshape. 
array_3d = np.random.randint(1, 60, (3, 4, 2))
array_3d

array([[[37, 23,  2, 38, 18],
        [26, 40, 44, 27, 43],
        [35,  2, 16, 51, 59],
        [ 4, 35, 40, 52, 11]],

       [[28, 48, 40, 17,  7],
        [57, 32, 33, 17, 27],
        [ 4, 33, 20, 57, 59],
        [11, 13, 37, 38, 17]],

       [[43, 12, 25, 30,  3],
        [54, 17,  4, 20, 37],
        [19, 22, 42, 19, 32],
        [40,  3, 20, 53, 54]]])

In [53]:
# Utilizar transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 2, 4).
array_transpose2 = np.transpose(array_3d,(0, 2, 1))
array_transpose2

array([[[37, 26, 35,  4],
        [23, 40,  2, 35],
        [ 2, 44, 16, 40],
        [38, 27, 51, 52],
        [18, 43, 59, 11]],

       [[28, 57,  4, 11],
        [48, 32, 33, 13],
        [40, 33, 20, 37],
        [17, 17, 57, 38],
        [ 7, 27, 59, 17]],

       [[43, 54, 19, 40],
        [12, 17, 22,  3],
        [25,  4, 42, 20],
        [30, 20, 19, 53],
        [ 3, 37, 32, 54]]])

# Preguntas teóricas:
6. ¿Qué diferencia existe entre el reshape y el transpose?:
- Reshape: Es una función que se utiliza para cambiar la forma de un array sin cambiar sus datos. Puedes especificar la nueva forma deseada del array, y NumPy se encargará de reorganizar los elementos para ajustarse a esa nueva forma. Es importante destacar que el número total de elementos debe ser el mismo antes y después de la operación de reshape.
- Transpose: Es una función que se utiliza para permutar los ejes de un array según un orden específico que se especifica como argumento. Puedes cambiar el orden de las dimensiones del array. 


7. ¿Y entre el transpose y el swapaxes?:
- Transpose: Es una función que se utiliza para permutar los ejes de un array según un orden específico que se especifica como argumento. Puedes cambiar el orden de las dimensiones del array. 
- Swapaxes: Es una función específica que se utiliza para intercambiar dos ejes particulares de un array.

Resumen: Transpose, permite especificar un orden completo para los ejes y swapaxes te permite intercambiar dos ejes específicos.



# Funciones Aritméticas y Estadísticas:

1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [4]:
arrayfunciones = np.round(np.random.rand(2, 3, 5), 1)
arrayfunciones

array([[[0.7, 0.8, 0.2, 0. , 0.6],
        [0.8, 0.8, 0.8, 0.5, 0.8],
        [0.8, 0.9, 0.5, 0.4, 0.3]],

       [[0.1, 0.3, 0.2, 0.6, 0.8],
        [0.1, 0.9, 0. , 0.6, 0.6],
        [0.2, 0.9, 0.5, 0.9, 0.6]]])

2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente.
Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero
basándonos en los valores del primer array bajo las siguientes condiciones:
Si el valor del array es igual que la media, se reemplaza por "A".
Si el valor del array es mayor que la media, se reemplaza por "B".
Si el valor del array es menor que la media, se reemplaza por "C".
Si el valor es igual que el máximo, se reemplaza por "D".
Si el valor es igual que el mínimo, se reemplaza por "E".

-  a modo de ejemplo. Si tenemos el siguiente array
[[[0.4, 0.7, 0.2, 0.9, 0.2],
 [0.1, 0.9, 0.6, 0.1, 0.2],
 [1. , 0.2, 0.1, 0.8, 0.3]],
[[0. , 0.3, 0.4, 0.5, 0.1],
 [0.5, 0.7, 0.9, 0. , 0.8],
 [0.5, 0.3, 0.5, 0.8, 0.1]]])
-  sabiendo que la media es 0.4 y el máximo es 1.0 y el mínimo es:     0.0
-  nuestro array vacío debería quedar como este: 
[[["A", "B", "C", "B", "C"],
 ["C", "B", "B", "C", "C"],
 ["D" , "C", "C", "B", "C"]],
[["E" , "C", "A", "B", "C"],
 ["B", "B","B", "E" , "B"],
 ["B", "C", "B", "B", "C"]]]

In [5]:
arraycompleto = np.empty((2,3,5))
arraycompleto

array([[[0.7, 0.8, 0.2, 0. , 0.6],
        [0.8, 0.8, 0.8, 0.5, 0.8],
        [0.8, 0.9, 0.5, 0.4, 0.3]],

       [[0.1, 0.3, 0.2, 0.6, 0.8],
        [0.1, 0.9, 0. , 0.6, 0.6],
        [0.2, 0.9, 0.5, 0.9, 0.6]]])

In [6]:
# Calcular la media, el máximo y el mínimo del array original
media = np.mean(arraycompleto)
media

0.5399999999999999

In [7]:
maximo = np.max(arraycompleto)
maximo

0.9

In [8]:
minimo = np.min(arraycompleto)
minimo

0.0

In [9]:
# Iterar sobre los elementos del array completo y aplicar las condiciones necesarias
for i, elemento in enumerate(arraycompleto):
    for j, fila in enumerate(elemento):
        for k, valor in enumerate(fila):
            valor = arraycompleto[i, j, k]
            
            if valor == maximo:
                arraycompleto[i, j, k] = 4  # Reemplazar "D" por 4
                
            elif  valor == minimo:
                arraycompleto[i, j, k] = 5  # Reemplazar "E" por 5
                                
            elif valor == media:
                arraycompleto[i, j, k] = 1  # Reemplazar "A" por 1
                
            elif valor > media:
                arraycompleto[i, j, k] = 2  # Reemplazar "B" por 2
                
            elif valor < media:
                arraycompleto[i, j, k] = 3  # Reemplazar "C" por 3
                
print(arraycompleto)


[[[2. 2. 3. 5. 2.]
  [2. 2. 2. 3. 2.]
  [2. 4. 3. 3. 3.]]

 [[3. 3. 3. 2. 2.]
  [3. 4. 5. 2. 2.]
  [3. 4. 3. 4. 2.]]]


In [10]:
# Iterar sobre los elementos del array completo y aplicar las condiciones necesarias
for i in arraycompleto:
    arrayvacia1 = []
    for j in i:
        arrayvacia2 = []
        for k in j:
            valor = arraycompleto[i, j, k]
            
            if valor == maximo:
                arrayvacia2.append("D")
                
            elif  valor == minimo:
                arrayvacia2.append("E")
                
            elif valor == media:
                arrayvacia2.append("A")
                
            elif valor > media:
                arrayvacia2.append("B")
                
            elif valor < media:
                arrayvacia2.append("C")
            
        arrayvacia1.append(arrayvacia2)
        
        print(arraycompleto)
            
    arraycompleto.append(arrayvacia1)


IndexError: arrays used as indices must be of integer (or boolean) type